services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: n8n_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - n8n_postgres_data:/var/lib/postgresql/data
    networks:
      - n8n_network

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
      N8N_DEFAULT_BINARY_DATA_MODE: filesystem

      WEBHOOK_URL: https://${DOMAIN}
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      TZ: America/Argentina/Buenos_Aires

    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n_network
    depends_on:
      - postgres

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - n8n_network

    # --- SERVICIOS DE CHATWOOT ---
  redis:
    image: redis:7-alpine
    container_name: chatwoot_redis
    restart: unless-stopped
    command: redis-server --requirepass {$REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - n8n_network

  chatwoot:
    image: chatwoot/chatwoot:latest
    container_name: chatwoot_web
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      - FRONTEND_URL=https://${CHATWOOT_DOMAIN}
      - SECRET_KEY_BASE=${CHATWOOT_SECRET_KEY_BASE}
      - POSTGRES_DATABASE=chatwoot
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_URL=redis://default:${REDIS_PASSWORD}@redis:6379
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    networks:
      - n8n_network

  chatwoot-worker:
    image: chatwoot/chatwoot:latest
    container_name: chatwoot_worker
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    environment:
      - FRONTEND_URL=https://${CHATWOOT_DOMAIN}
      - SECRET_KEY_BASE=${CHATWOOT_SECRET_KEY_BASE}
      - POSTGRES_DATABASE=chatwoot
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_URL=redis://default:${REDIS_PASSWORD}@redis:6379
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    networks:
      - n8n_network

networks:
  n8n_network:

volumes:
  caddy_data:
  caddy_config:
  n8n_postgres_data:
  n8n_data:
  redis_data:
